# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/child_growth_tracking_system
#     username: root
#     password: 2029666
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     database-platform: org.hibernate.dialect.MySQLDialect
#     hibernate:
#       ddl-auto: update
#     show-sql: true
  

  

